### ISSUE TITLE
ANSI on Windows, perhaps use colorama

### ISSUE THREAD

**Issue by timcera** [Snaipe/python-rst2ansi#3]
Haven't tested this yet, but it seems that ANSI on Windows is problematic.  Found [colorama](https://pypi.python.org/pypi/colorama) which looks to be a good choice for displaying ANSI on Windows.

**Comment by Snaipe** [comment]
Colorama actually lets you print ANSI formatted strings onto your terminal:

``` python
import colorama
from rst2ansi import rst2ansi

colorama.init();
print(rst2ansi('Hello, **World**!'))
```

The module purposely avoids having any hard dependency over a specific ANSI printer.
