### ISSUE TITLE
rst2ansi not rendering option lists correctly.

### ISSUE THREAD

**Issue by timcera** [Snaipe/python-rst2ansi#4]
The attached file has option lists that rst2ansi does not correctly render.  They are rendered using other utilities, specifically "rst2man" that comes with docutils.

[test.txt](https://github.com/Snaipe/python-rst2ansi/files/202969/test.txt)

instead of the following from "rst2man":

```
              --type <str>
                     The plot type.  Defaults to 'time'.  Can be one of the following:

                     'time' standard time series plot,

                     'xy'   (x,y) plot, also know as a scatter plot,

                     'double_mass'
                            (x,y) plot of the cumulative sum of x and y,
```

"rst2ansi" gives:

```
--type<str>The plot type. Defaults to 'time'. Can be one of the following:

'time'standard time series plot,

'xy'(x,y) plot, also know as a scatter plot,

'double_mass'(x,y) plot of the cumulative sum of x and y,
```

Both correctly render the tables in the file.

This is using Python 3.4.

**Comment by Snaipe** [comment]
Commit 712a481 should address this. It's a work in progress more than anything, but at least it seems to be doing its job.

**Comment by timcera** [comment]
Fantastic.  It looks nice.  The definition list has an extra line, but not a big deal at all.

Thanks!

Kindest regards,
Tim
