### ISSUE TITLE
Request for new version posted to pypi

### ISSUE THREAD

**Issue by timcera** [Snaipe/python-rst2ansi#7]
It would be helpful to one of my other projects to have the option list implementation that is in git to be available in a version from PyPI.

Kindest regards,
Tim

**Comment by Snaipe** [comment]
Right -- sorry, I haven't had the liberty to really work on most of my projects recently. Will release a new patch version ASAP.

**Comment by Snaipe** [comment]
Released as v0.1.5.

**Comment by timcera** [comment]
No problem.  Thanks!
